sonar.projectKey=SmilyTheOne_biowatch
sonar.organization=smilytheone

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc,**/.venv/**,**/coverage/**,**/*.min.js,**/migrations/**

sonar.sourceEncoding=UTF-8
